apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-config
  namespace: fcg
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Jwt__Issuer: "fcg-users-api"
  Jwt__Audience: "fcg-platform"
  Jwt__AccessTokenExpirationMinutes: "15"
  Jwt__RefreshTokenExpirationDays: "7"
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__VirtualHost: "/"
  RabbitMQ__Username: "guest"
  SeedAdmin__Habilitado: "true"
  SeedAdmin__Email: "admin@fcg.com"
  SeedAdmin__Nome: "Admin FCG"
