apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
  namespace: fcg
type: Opaque
# Valores em base64: echo -n "valor" | base64
data:
  # fcg-super-secret-key-change-in-production-min32chars!
  Jwt__Secret: ZmNnLXN1cGVyLXNlY3JldC1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24tbWluMzJjaGFycyE=
  # Host=postgres;Port=5432;Database=fcg;Username=fcg_app;Password=fcg_app_dev
  ConnectionStrings__Postgres: SG9zdD1wb3N0Z3JlcztQb3J0PTU0MzI7RGF0YWJhc2U9ZmNnO1VzZXJuYW1lPWZjZ19hcHA7UGFzc3dvcmQ9ZmNnX2FwcF9kZXY=
  # guest
  RabbitMQ__Password: Z3Vlc3Q=
  # TrocarEm@2026
  SeedAdmin__Senha: VHJvY2FyRW1AMjAyNg==
