apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: fcg
  labels:
    app: users-api
spec:
  selector:
    app: users-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
# NodePort para acesso local durante testes (opcional em produção)
apiVersion: v1
kind: Service
metadata:
  name: users-api-external
  namespace: fcg
spec:
  selector:
    app: users-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30081
  type: NodePort
